name: Build & Push OCI Provider (ARM64)

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.OCI }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: build/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/oci-secrets-provider:arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
